name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Set this to your project's node.js version

      - name: Install Dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn test

      - name: Build
        run: CI=false yarn build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }} # Using the secret as an environment variable

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
